### ISSUE TITLE
Board issue

### ISSUE THREAD

**Issue by chrisys** [cryxli/sr201#1]
@cryxli do you ever find you have a problem where the boards seem to lock up and stop responding to requests? Occasionally mine will stop responding to ping and just fall off the network.

**Comment by cryxli** [comment]
Hi Chris,
I was planning on using the board in a permanent setup, but so far I haven't been building anything. Therefore, I do not have any long-time experience. About 3h, max.
I remember that one of the chips on the board is dedicated to handling ethernet communication. You may want to have a look at its specs for any clue.

Can you provide us with some numbers about how the failure manifests?
- E.g., how long before it disconnects?
- How many commands do you send and how often? - May indicate too many requests, or, too few. Perhaps it need a certain "keep alive" load...
- If you have more than one board, does it happen with all of them? - May indicate a problem with only one board, or a design flaw.
- How do you power the board? - 5V USB, or the 9-24V terminal. - Does your power source have any spikes or is it "smoothed enough" to drive micro chips? - I do not know how good the board is protected against such things.
- I don't think it is relevant, but do you switch heavy loads with the relays?
- It may sound stupid, but have you accidentally shorted something on the board? - E.g. I do not know how much for how long you can drive off of the additional 3.3V pins. (Channel 3 to 8 on a 2 relays board.) 
- Whatever else you think may be noteworthy...

Perhaps I can emulate your setup and at least confirm your observations.

**Comment by chrisys** [comment]
Hey @cryxli thanks for your reply. I was just intrigued to see if you had any issues. Mine are on a busy network and I suspect it's the sheer amount of broadcast traffic that takes them down. I have them running a lot of floodlights in full production mode so will keep you up to date with how they run.

Edit: forgot to mention, I have now put the boards onto their own VLAN to isolate from the rest of the network and hopefully mitigate any problems caused by other network traffic.
