### ISSUE TITLE
Cloud Service

### ISSUE THREAD

**Issue by anakhaema** [cryxli/sr201#2]
Not an issue as such, but I've worked out how the on-board cloud remote control system is designed - in case anyone wanted to add the feature (my testing was all in C, not java) or was otherwise curious.

When operational, the relay attempts to establish a standard HTTP connection to the server (default connect.tutuuu.com, port 80) with a standard SYN request.
Once a connection is made, the relay dumps TCP data immediately in the form:
```
POST /SyncServiceImpl.svc/ReportStatus HTTP/1.1
User-Agent: SR-201W/M96Y
Content-Type: application/json
Host: connect.tutuuu.com
Content-Length: 30

"F0123456789ABCXXXXXX00000000"
```
The first 13 characters after 'F' is the device serial (all hex), followed by the 6-digit password (numerical, plain text) and then the 8-digit current relay state.

There is then a 60 second TTL for the response, which should be of the form: 
```
HTTP/1.1 200 OK
Date: Mon, 01 Jan 1980 00:00:00 GMT
Server: Microsoft-IIS/6.0
X-Powered-By: ASP.NET
X-AspNet-Version: 2.0.50727
Cache-Control: private
Content-Type: application/json; charset=utf-8
Content-Length: 3

"A"
```

This is the constant-state response - simply indicating that both endpoints are live and ready.
(As with standard HTTP, all lines must terminate with the windows style newline "\r\n")

To change the relay states, the final line must change from `"A"` to any of the standard port commands, until the change is acknowledged in the subsequent "pings".
Eg. `"A11"` to switch relay 1 on, etc.

**Comment by cryxli** [comment]
Hi Sam, thanks for sharing your knowledge with us!

Until I find the time to create a code example in the repo, I simply copied your message to the new wiki page [Cloud Service](https://github.com/cryxli/sr201/wiki/Cloud-Service).

**Comment by hobpet** [comment]
Hello, I've created a sample PHP example. Do you mind if I create a pull request for that?
Basically what that does is that it implements the /SyncServiceImpl.svc/ReportStatus, stores the status of the relays in a file and reads another file with the command to execute.
There is a web form to get the status from the file and set the command to the command file.
The file name is generated from the device ID and the password (hashed) so that is a kind of login to prevent unauthorized access. Someone can add more protection, but I just created that for a quick test.

**Comment by cryxli** [comment]
Sure. That would be great.

**Comment by hobpet** [comment]
Done! Let me know your feedback, suggestions. (Caveat: I'm not a professional php developer, the sole reason I created this was that this seemed to be the quickest and easiest way to use the Cloud Service without talking to Chinese servers. :) )

**Comment by cryxli** [comment]
There is not much feedback to be had.
The code looks much cleaner than the Spaghetti code I would produce in PHP.
I cannot read apache rewrite rules. Therefore I assume they work.

I also think it serves the purpose to show more than just the basics needed for a "proper" implementation. The live hosting to test both the boards and the PHP scripts is a great idea!

In my opinion the ticket is more than solved with the current example. What do you guys think?

**Comment by hobpet** [comment]
I agree, I copied over most of the comments from @anakhaema to the readme.md and your wiki article is also pretty complete so I also think this can me marked as solved.
