### ISSUE TITLE
Starting application or sending HTTP-commands

### ISSUE THREAD

**Issue by ZonPV** [cryxli/sr201#5]
Client-application runs in Windowsenvironment for now.
But I want to use this solution in my domotica-app (Domoticz) on the Synology. Then I can use timers to pull and release relays on time.

I have a question about starting the application with parameters or directly sending commands to the relayboard to pull or release the relays.

Can you give an example, or explain how to use the SR201-server to change the state of the relays. Or is it possible to start the application with parameters? Domoticz can start a script with the commands of can send a http-requests. But I have no idea about the syntax. Maybe you can give me some explanation?

Thank you in advance.

**Comment by cryxli** [comment]
I take an educated guess: With Synology you mean a Linux based NAS. Therefore drop the whole Java app idea, that is overkill. It's purpose is to illustrate how the communication with the SR201 could look like. But what is really going on in the background is explained in the wiki: [Switch commands](https://github.com/cryxli/sr201/wiki/Switch-commands) ff.

Therefore, I suggest you use a linux script to send the commands directly:

```
# reset (open) all relays
echo -n "2X" | nc 192.168.0.201 6722
```

or

```
# close relay 1
echo -n "11" | nc 192.168.0.201 6722
```

etc.

- `echo` <=> write a text
- `echo -n` <=> write a text, then a new line
- `nc <IP> <port>` <=> connect netcat to an IP address at a specific remote port
- all together: pipe the result of echo into netcat

**Comment by ZonPV** [comment]
H Urs,

Thnx for quick reply and clear answer. I will give it a try later on this weekend. I am not to familiar with Linux.
I found some information in your Wiki but that was not sufficient for me. Sorry for that. Thanks for your explanation. Writing batchfiles in DOS is still here...

**Comment by ZonPV** [comment]
It all works as explained!!
Still a question: has to do with Linux I guess.
When i execute the script in Putty on the NAS: it takes about 5 seconds before the prompt is back. Is there need for an extra code to close the file by netcat?

![relay1-on](https://cloud.githubusercontent.com/assets/11488827/26748025/846064ae-47fa-11e7-9cfd-7d183ac6d69e.PNG)

**Comment by cryxli** [comment]
Funny thing: The system with which I tested netcat uses other defaults than a standard debian.

1) The 5 seconds appear to be a default timeout of netcat before it closes the connection. You can lower it to 1 second `-w 1`
2) When writing a proper script, I would try to tell the environment how to execute it `#!/usr/bin/bash`, e.g.
3) If the calling application expects a certain error code, I'd terminate the script with `exit 0` to indicate success.
4) Since the answer of the delay does not matter, drop it <=> send it to `/dev/null`

```
#!/usr/bin/env bash
echo -n "11" | nc -n -w 1 192.168.1.100 6722 &>/dev/null
exit 0
```

4b) Since the answer does not matter, you could use UDP

```
#!/usr/bin/env bash
echo -n "11" | nc -n -u -w 1 192.168.1.100 6722 &>/dev/null
exit 0
# Depending on your network layout this may not reach its destination !
```

Read the `man nc` page of netcat on your linux system to get more options.

**Comment by ZonPV** [comment]
Many thanks for quick reply!
It looks as if netcat is waiting for response or timeout.
I use Netcat 0.7.1. This version is the only package that i can download for my Synology NAS
 
Option -w 1 makes no sense. Neither an error as long as I did not lower it to zero.. Than the relay does not react at all when i execute the file. The prompt is right there...

Option -u gave no response when I execute the file.

BUT:
Your final sentence was the solution! I read the manual and tried the option -c 
  -c, --close                close connection on EOF from stdin

It did the job! Quick response and no delays any more!

This is the right code:
![relay1-on](https://cloud.githubusercontent.com/assets/11488827/26754371/1e59215c-487a-11e7-9258-c69a3154b1d2.PNG)

THANKS A LOT

**Comment by FabrizioRoncato** [comment]
@ZonPV Hello Pieter, sorry for resuming an old post, but I'm trying to get the right code for closing the relay at the release of the "dummy device" in domoticz, I wrote the 2 scripts for the on/off as:

ON
`echo -n "11" | nc 192.168.0.99 6722`

OFF
`echo -n "21" | nc 192.168.0.99 6722`

But every time I turn off the virtual switch in domoticz only after 15s I get the relay released, how should I have to add in the code to get rig of 15s idle?

Thank you in advance!!!
Fabrizio

**Comment by FabrizioRoncato** [comment]
> @ZonPV Hello Pieter, sorry for resuming an old post, but I'm trying to get the right code for closing the relay at the release of the "dummy device" in domoticz, I wrote the 2 scripts for the on/off as:
> 
> ON
> `echo -n "11" | nc 192.168.0.99 6722`
> 
> OFF
> `echo -n "21" | nc 192.168.0.99 6722`
> 
> But every time I turn off the virtual switch in domoticz only after 15s I get the relay released, how should I have to add in the code to get rig of 15s idle?
> 
> Thank you in advance!!!
> Fabrizio

I finally sorted out changing the line like this:

ON
`echo -n "11" | nc -n -w 1 192.168.0.99 6722`

OFF
`echo -n "21" | nc -n -w 1 192.168.0.99 6722`

Now the relay turn on and off without delay! Super!

Hope this will help for the future

Fabrizio

**Comment by zibensdraugs** [comment]
Hello, how to do this in netcat from windows machine?

**Comment by cryxli** [comment]
Hi zibensdraugs
I have never done network stuff with windows batch files. I simply cannot help you there.

What I would check:

- Does windows have any functionality similar to netcat? - No clue.
- Is there a windows port of netcat? - Yes: https://eternallybored.org/misc/netcat/
- Do the above mentioned snippets work with one of the two...

Hope you'll find something to help you!

**Comment by FabrizioRoncato** [comment]
Hello,

back to this issue with a new problem, I have installed Domoticz with docker on my Synology, problem is that the script .sh:

`echo -n "11" | nc -n -w 1 192.168.0.99 6722`

that was running okay on my raspberry is not working in my docker enviormental.

I tried to install netcat in the docker with:

apt-get update
apt-get install netcat

but it returns me with some warning:

`update-alternatives: warning: skip creation of /usr/share/man/man1/nc.1.gz because associated file /usr/share/man/man1/nc.traditional.1.gz (of link group nc) doesn't exist`
`update-alternatives: warning: skip creation of /usr/share/man/man1/netcat.1.gz because associated file /usr/share/man/man1/nc.traditional.1.gz (of link group nc) doesn't exist`


The action script in domoticz logs appear to be okay, but the relay doesn't turn on or off when the script run from domoticz

**Comment by FabrizioRoncato** [comment]
> Hello,
> 
> back to this issue with a new problem, I have installed Domoticz with docker on my Synology, problem is that the script .sh:
> 
> `echo -n "11" | nc -n -w 1 192.168.0.99 6722`
> 
> that was running okay on my raspberry is not working in my docker enviormental.
> 
> I tried to install netcat in the docker with:
> 
> apt-get update apt-get install netcat
> 
> but it returns me with some warning:
> 
> `update-alternatives: warning: skip creation of /usr/share/man/man1/nc.1.gz because associated file /usr/share/man/man1/nc.traditional.1.gz (of link group nc) doesn't exist` `update-alternatives: warning: skip creation of /usr/share/man/man1/netcat.1.gz because associated file /usr/share/man/man1/nc.traditional.1.gz (of link group nc) doesn't exist`
> 
> The action script in domoticz logs appear to be okay, but the relay doesn't turn on or off when the script run from domoticz

Finally resolve the problem.

You need to install netcat from inside the docker terminal, next test script in the docker and will succesfully return with on and off code "10000000" "00000000".

**Comment by StefanoVitale69** [comment]
HI, I use the SR201-server with Home Assistant
I would like to use the sr201-server command line with netcat on windows 10.
But if I use echo -n "11" | nc -n -w 1 192.168.1.100 6722 does not send the command but only reads the status.
And as if he does not see "11"
I have tried so many ways but it doesn't send commands it always reads only the status.
How can I fix?

**Comment by StefanoVitale69** [comment]
![Screenshot (120)](https://user-images.githubusercontent.com/34214967/235424909-18032f32-79df-453a-b836-fc5080ebef86.png)

**Comment by StefanoVitale69** [comment]
With Putty it works fine. But I would like to use netcat to create an executable .bat file to run at set times so as to compensate for the lack of a clock on the board
